### PR TITLE
Add raw tests results into results object

### PR DESCRIPTION
**Pull request by MoOx**
Close #3
Close https://github.com/conradz/wd-tap-runner/pull/3

### CODE REVIEW

**Comment by conradz** [comment]
Can you remove the version change? I think this should be a minor version increment since there was new stuff added. Also, I usually use `npm version` to increment and tag the version.

**Comment by MoOx** [comment]
Done !

**Comment by MoOx** [comment]
I just renamed the commit :)

**Comment by conradz** [comment]
Released as v1.0.0, now we have a stable version! Also I hooked up Travis to run automated tests.

**Comment by MoOx** [comment]
Awesome.

**Pull request merged**
